version: "3.9"

networks:
  appnet:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_eee
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - appnet

  laravel-app:
    build:
      context: ../car_rent_backend
      dockerfile: Dockerfile
    container_name: laravel-app
    env_file:
      - ../car_rent_backend/.env
    volumes:
      - ../car_rent_backend:/var/www/html
      - storage_data:/var/www/html/storage
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - appnet
    working_dir: /var/www/html
    ports:
      - "8000:8000"

  php-worker:
    build:
      context: ../car_rent_backend
      dockerfile: Dockerfile
    container_name: php-worker
    command: php artisan queue:work --tries=3
    env_file:
      - ../car_rent_backend/.env
    depends_on:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - ../car_rent_backend:/var/www/html
      - storage_data:/var/www/html/storage
    networks:
      - appnet

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - laravel-app
    networks:
      - appnet

  go-export:
    build:
      context: ../car-export-go
      dockerfile: Dockerfile
    container_name: go-export
    env_file:
      - ../car-export-go/.env
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - appnet
    ports:
      - "8002:8002"

volumes:
  mysql_data:
  storage_data:
